// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MealController from "./meal_controller.js"
application.register("meal", MealController)

import NewRecipeController from "./new_recipe_controller.js"
application.register("new-recipe", NewRecipeController)

import RecipeController from "./recipe_controller.js"
application.register("recipe", RecipeController)

import StatisticChartController from "./statistic_chart_controller.js"
application.register("statistic-chart", StatisticChartController)

import StopController from "./stop_controller.js"
application.register("stop", StopController)

import TransactionController from "./transaction_controller.js"
application.register("transaction", TransactionController)
