FROM ruby:3.3

WORKDIR /gruby

COPY . /gruby

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt update \
  && apt install -y sqlite3 postgresql-client nodejs \
  && npm install --global yarn \  
  && gem install bundler --version 2.5.6 \
  && gem install foreman \
  && bundle install
